version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Walker@90
      - MYSQL_DB=medico

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Walker@90
      MYSQL_DATABASE: medico
      MYSQL_USER: root
      MYSQL_PASSWORD: Walker@90
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
